<div class="d-flex justify-content-between align-items-center mb-4">
    <h2>System Report</h2>
    <div>
        <button onclick="window.print()" class="btn btn-success">
            <i class="bi bi-printer"></i> Print Report
        </button>
        <a href="index.php?controller=dashboard&action=index" class="btn btn-secondary">
            <i class="bi bi-arrow-left"></i> Back to Dashboard
        </a>
    </div>
</div>

<!-- Filter Section -->
<div class="card mb-4">
    <div class="card-header">
        <h5 class="mb-0"><i class="bi bi-funnel me-2"></i>Filter Report Data</h5>
    </div>
    <div class="card-body">
        <form method="GET" action="index.php" class="row g-3">
            <input type="hidden" name="controller" value="report">
            <input type="hidden" name="action" value="index">
            
            <div class="col-md-3">
                <label for="doc_year" class="form-label">Document Year</label>
                <select class="form-select" id="doc_year" name="doc_year">
                    <option value="">All Years</option>
                    <?php foreach($available_years as $year): ?>
                        <option value="<?php echo $year; ?>" <?php echo ($filters['doc_year'] ?? '') == $year ? 'selected' : ''; ?>>
                            <?php echo $year; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            
            <div class="col-md-3">
                <label for="office_type_id" class="form-label">Office Type</label>
                <select class="form-select" id="office_type_id" name="office_type_id">
                    <option value="">All Office Types</option>
                    <?php foreach($office_types as $type): ?>
                        <option value="<?php echo $type['id']; ?>" <?php echo ($filters['office_type_id'] ?? '') == $type['id'] ? 'selected' : ''; ?>>
                            <?php echo htmlspecialchars($type['type_name']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            
            <div class="col-md-3">
                <label for="school_id" class="form-label">School/Office</label>
                <select class="form-select" id="school_id" name="school_id">
                    <option value="">All Schools/Offices</option>
                    <?php foreach($all_schools as $school_item): ?>
<option value="<?php echo $school_item['id']; ?>" <?php echo ($filters['school_id'] ?? '') == $school_item['id'] ? 'selected' : ''; ?>>
                            <?php echo htmlspecialchars($school_item['school_name']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            
            <div class="col-md-3 d-flex align-items-end">
                <button type="submit" class="btn btn-primary w-100 me-2">
                    <i class="bi bi-search"></i> Apply Filters
                </button>
                <a href="index.php?controller=report&action=index" class="btn btn-secondary w-100">
                    <i class="bi bi-arrow-repeat"></i> Reset
                </a>
            </div>
        </form>
    </div>
</div>

<!-- Report Header -->
<div class="card mb-4">
    <div class="card-body text-center">
        <h3>RECORDS MANAGEMENT SYSTEM</h3>
        <h5>System Report</h5>
        <p class="text-muted">Generated on: <?php echo $report_date; ?></p>
        <p class="text-muted">Generated by: <?php echo $user_name; ?> (<?php echo ucfirst($user_role); ?>)</p>
        <?php if(!empty($filters)): ?>
            <div class="alert alert-info">
                <strong>Applied Filters:</strong><br>
                <?php if(!empty($filters['doc_year'])) echo "Year: {$filters['doc_year']} | "; ?>
                <?php if(!empty($filters['office_type_id'])) echo "Office Type: Filtered | "; ?>
                <?php if(!empty($filters['school_id'])) echo "School: Filtered"; ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<!-- Document Type Analytics Table -->
<div class="card mb-4">
    <div class="card-header">
        <h5 class="mb-0"><i class="bi bi-pie-chart me-2"></i>Document Type Analytics</h5>
        <small class="text-muted">Number of documents per document type</small>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead class="table-dark">
                    <tr>
                        <th>Document Type</th>
                        <th>Number of Documents</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(count($document_type_stats) > 0): ?>
                        <?php foreach($document_type_stats as $stat): ?>
                        <tr>
                            <td>
                                <div class="d-flex align-items-center">
                                    <div class="type-color" style="background: <?php 
                                        $colors = ['#667eea', '#28a745', '#ffc107', '#dc3545', '#17a2b8', '#6f42c1', '#fd7e14'];
                                        echo $colors[array_rand($colors)];
                                    ?>;"></div>
                                    <strong class="text-dark"><?php echo htmlspecialchars($stat['document_type']); ?></strong>
                                </div>
                              </td>
                            <td>
                                <span class="badge bg-primary"><?php echo number_format($stat['total']); ?></span>
                              </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="2" class="text-center py-4">
                                <i class="bi bi-inbox" style="font-size: 48px; color: #666;"></i>
                                <p class="mt-2 text-muted">No documents found</p>
                              </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
                <tfoot class="table-light">
                    <tr>
                        <th>Total</th>
                        <th><?php echo number_format($total_documents); ?></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<!-- Schools by Document Count Table -->
<div class="card mb-4">
    <div class="card-header">
        <h5 class="mb-0"><i class="bi bi-building me-2"></i>Schools by Document Count</h5>
        <small class="text-muted">Number of documents per school/office</small>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead class="table-dark">
                    <tr>
                        <th>#</th>
                        <th>School/Office Name</th>
                        <th>Number of Documents</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(count($schools_by_document_count) > 0): ?>
                        <?php $rank = 1; ?>
                        <?php foreach($schools_by_document_count as $school_stat): ?>
                        <tr>
                            <td>
                                <?php 
                                if($rank == 1) echo '<span class="rank-icon">🥇</span>';
                                elseif($rank == 2) echo '<span class="rank-icon">🥈</span>';
                                elseif($rank == 3) echo '<span class="rank-icon">🥉</span>';
                                else echo '<span class="rank-number">' . $rank . '</span>';
                                ?>
                              </td>
                            <td>
                                <strong class="text-dark"><?php echo htmlspecialchars($school_stat['school_name']); ?></strong>
                              </td>
                            <td>
                                <span class="badge bg-primary"><?php echo number_format($school_stat['doc_count']); ?></span>
                              </td>
                            </tr>
                        <?php $rank++; ?>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="3" class="text-center py-4">
                                <i class="bi bi-building" style="font-size: 48px; color: #666;"></i>
                                <p class="mt-2 text-muted">No schools/offices found</p>
                              </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
                <tfoot class="table-light">
                    <tr>
                        <th colspan="2">Total Schools with Documents</th>
                        <th><?php echo number_format(count($schools_by_document_count)); ?></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<!-- Top Schools and Documents by Year -->
<div class="row">
    <div class="col-md-6">
        <div class="card h-100">
            <div class="card-header">
                <h5 class="mb-0"><i class="bi bi-trophy me-2"></i>Top 10 Schools by Document Count</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <tr>
                                <th>Rank</th>
                                <th>School/Office</th>
                                <th>Office Type</th>
                                <th>Documents</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(count($top_schools) > 0): ?>
                                <?php $rank = 1; ?>
                                <?php foreach($top_schools as $school_item): ?>
                                <tr>
                                    <td>
                                        <?php 
                                        if($rank == 1) echo '🥇';
                                        elseif($rank == 2) echo '🥈';
                                        elseif($rank == 3) echo '🥉';
                                        else echo $rank;
                                        ?>
                                      </td>
                                    <td>
                                        <strong class="text-dark"><?php echo htmlspecialchars($school_item['school_name']); ?></strong>
                                      </td>
                                    <td>
                                        <span class="badge bg-secondary"><?php echo htmlspecialchars($school_item['office_type_name'] ?? 'N/A'); ?></span>
                                      </td>
                                    <td>
                                        <span class="badge bg-success"><?php echo number_format($school_item['doc_count']); ?></span>
                                      </td>
                                </tr>
                                <?php $rank++; ?>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <tr>
                                    <td colspan="4" class="text-center py-4">
                                        <i class="bi bi-bar-chart" style="font-size: 48px; color: #666;"></i>
                                        <p class="mt-2 text-muted">No data available</p>
                                      </td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card h-100">
            <div class="card-header">
                <h5 class="mb-0"><i class="bi bi-calendar me-2"></i>Documents by Year</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <tr>
                                <th>Year</th>
                                <th>Number of Documents</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(count($documents_by_year) > 0): ?>
                                <?php foreach($documents_by_year as $year_stat): ?>
                                <tr>
                                    <td>
                                        <strong class="text-dark"><?php echo $year_stat['doc_year'] ?: 'No Year'; ?></strong>
                                      </td>
                                    <td>
                                        <span class="badge bg-primary"><?php echo number_format($year_stat['total']); ?></span>
                                      </td>
                                </tr>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <tr>
                                    <td colspan="2" class="text-center py-4">
                                        <i class="bi bi-calendar-x" style="font-size: 48px; color: #666;"></i>
                                        <p class="mt-2 text-muted">No data available</p>
                                      </td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                        <tfoot class="table-light">
                            <tr>
                                <th>Total</th>
                                <th><?php echo number_format($total_documents); ?></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .table-bordered td, .table-bordered th {
        border: 1px solid #dee2e6;
        color: #212529;
    }
    
    .table tbody td {
        color: #212529;
    }
    
    .table thead th {
        color: white;
    }
    
    .text-dark {
        color: #212529 !important;
    }
    
    @media print {
        .no-print, .btn, .card-header .btn, .d-flex .btn, form, .filter-section, .action-buttons {
            display: none !important;
        }
        
        .card {
            break-inside: avoid;
            page-break-inside: avoid;
            border: 1px solid #ddd !important;
        }
        
        body {
            background: white;
            padding: 0;
            margin: 0;
        }
        
        .container {
            max-width: 100% !important;
            padding: 0 !important;
            margin: 0 !important;
        }
        
        .table-bordered td, .table-bordered th {
            border: 1px solid #000 !important;
        }
        
        .text-dark {
            color: #000 !important;
        }
    }
</style>